server:
  port: 7002
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka  #这个地址是 7000注册中心在 application.yml 中暴露出来额注册地址 （单机版）
  instance:
    instance-id: service7002 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址

spring:
  application:
    name: authorizecenter